apiVersion: apps/v1
kind: Deployment
metadata:
  name: civikzone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: civikzone
  template:
    metadata:
      labels:
        app: civikzone
    spec:
      containers:
      - name: civikzone
        image: varun5291/civikzone:v2
        ports:
        - containerPort: 8000
