# Generated by Django 6.0.1 on 2026-01-28 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Infrastructure', 'Infrastructure'), ('Sanitation', 'Sanitation'), ('Road', 'Road'), ('Water', 'Water'), ('Electricity', 'Electricity'), ('Other', 'Other')], max_length=50)),
                ('subcategory', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('complaint_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-complaint_date'],
            },
        ),
    ]
