# Generated by Django 6.0.1 on 2026-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='other_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='other_subcategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('1. Water Supply', '1. Water Supply'), ('2. Drainage & Stormwater', '2. Drainage & Stormwater'), ('3. Health & Hospitals/Dispensaries', '3. Health & Hospitals/Dispensaries'), ('4. Public Toilets', '4. Public Toilets'), ('5. Food & Hygiene', '5. Food & Hygiene'), ('6. Streetlights, Roads, and Footpaths', '6. Streetlights, Roads, and Footpaths'), ('7. Solid Waste Management', '7. Solid Waste Management'), ('8. Parks & Gardens', '8. Parks & Gardens'), ('9. Civic Centers & Administrative Services', '9. Civic Centers & Administrative Services'), ('10. Miscellaneous', '10. Miscellaneous'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subcategory',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='zone',
            field=models.CharField(choices=[('West Zone (Rander)', 'West Zone (Rander)'), ('Central Zone', 'Central Zone'), ('North Zone (Katargam)', 'North Zone (Katargam)'), ('East Zone – A(Varachha)', 'East Zone – A(Varachha)'), ('East Zone – B(Sarthana)', 'East Zone – B(Sarthana)'), ('South Zone – A (Udhna)', 'South Zone – A (Udhna)'), ('South Zone – B (Kanakpur)', 'South Zone – B (Kanakpur)'), ('South West Zone (Athwa)', 'South West Zone (Athwa)'), ('South East Zone (Limbayat)', 'South East Zone (Limbayat)')], max_length=100),
        ),
    ]
