# Generated by Django 4.2.7 on 2026-03-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.TextField(blank=True, help_text='Full address details (optional)', null=True),
        ),
    ]
