# Generated by Django 4.2.7 on 2026-03-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='resolved_date',
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
