# Generated by Django 5.2.8 on 2026-03-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='original_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_complaints', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
