# Generated by Django 5.2.8 on 2026-03-17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_duplicate_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStatusTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Timeline Event',
                'verbose_name_plural': 'Complaint Timeline Events',
                'db_table': 'complaint_status_timeline',
                'ordering': ['timestamp', 'id'],
                'unique_together': {('complaint', 'stage')},
            },
        ),
    ]
