# Generated by Django 5.2.8 on 2026-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100, unique=True)),
                ('zone_officers', models.PositiveIntegerField(default=0)),
                ('zone_complaints', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone Department',
                'verbose_name_plural': 'Zone Departments',
                'db_table': 'zone_departments',
                'ordering': ['zone_name'],
            },
        ),
    ]
