# Generated by Django 5.2.8 on 2026-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_zonedepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonedepartment',
            name='last_complaint_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
