# Generated by Django 5.2.8 on 2026-04-01 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_zonedepartment_last_complaint_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonedepartment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
