# Generated by Django 5.2.8 on 2026-04-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_alter_zonedepartment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonedepartment',
            name='updated_at',
        ),
    ]
