# Generated by Django 4.2.7 on 2026-04-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_remove_zonedepartment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
