# Generated by Django 5.2.8 on 2026-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_alter_complaint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Recipient Email'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reason',
            field=models.CharField(blank=True, help_text='e.g., password_reset, complaint_update, etc.', max_length=100, null=True, verbose_name='Notification Reason'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.TextField(),
        ),
    ]
