# Generated by Django 6.0.1 on 2026-02-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_customuser_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enable_gpt_codex',
            field=models.BooleanField(default=True, verbose_name='Enable GPT-5.2-Codex'),
        ),
    ]
