# Generated by Django 6.0.1 on 2026-02-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_otp_attempts_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
    ]
