# Generated by Django 5.2.8 on 2026-04-01 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('full', 'Full Access'), ('restricted', 'Restricted Access')], default='full', max_length=20)),
                ('can_manage_officers', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_manage_complaints', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_manage_system_settings', models.BooleanField(default=True)),
                ('can_modify_other_admins', models.BooleanField(default=False)),
                ('admin_code', models.CharField(max_length=50, unique=True, verbose_name='Admin Code')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SuperAdmin',
                'verbose_name_plural': 'SuperAdmins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.CharField(max_length=50, unique=True, verbose_name='Officer ID')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('office_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Office Phone')),
                ('office_address', models.TextField(blank=True, null=True, verbose_name='Office Address')),
                ('assigned_areas', models.TextField(blank=True, help_text='Comma-separated list of assigned areas/zones', null=True)),
                ('can_view_complaints', models.BooleanField(default=True)),
                ('can_update_complaint_status', models.BooleanField(default=True)),
                ('can_add_feedback', models.BooleanField(default=True)),
                ('can_generate_reports', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('complaints_handled', models.IntegerField(default=0, verbose_name='Total Complaints Handled')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_officers', to='accounts.superadmin')),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'ordering': ['-created_at'],
                'unique_together': {('officer_id', 'department')},
            },
        ),
    ]
