# Generated by Django 4.2.7 on 2026-04-07 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_officer_superadmin_profile_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verification_images/', verbose_name='Verification Image')),
                ('verification_type', models.CharField(choices=[('profile', 'Profile Verification'), ('complaint', 'Complaint Verification'), ('identity', 'Identity Verification'), ('location', 'Location Verification')], default='profile', max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Image',
                'verbose_name_plural': 'Verification Images',
                'ordering': ['-captured_at'],
            },
        ),
    ]
