# Generated by Django 4.2.7 on 2026-04-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_verificationimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationImage',
        ),
    ]
