# Generated by Django 4.2.7 on 2026-04-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_verificationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='zone',
        ),
    ]
